/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface TouchableBlur {
    '_blur': number;
  }
  interface TouchableElevate {
    'elevation': number;
  }
  interface TouchableHighlight {}
  interface TouchableOpacity {
    'opacity': number;
  }
  interface TouchableScale {
    'scale': number;
  }
}

declare global {


  interface HTMLTouchableBlurElement extends Components.TouchableBlur, HTMLStencilElement {}
  var HTMLTouchableBlurElement: {
    prototype: HTMLTouchableBlurElement;
    new (): HTMLTouchableBlurElement;
  };

  interface HTMLTouchableElevateElement extends Components.TouchableElevate, HTMLStencilElement {}
  var HTMLTouchableElevateElement: {
    prototype: HTMLTouchableElevateElement;
    new (): HTMLTouchableElevateElement;
  };

  interface HTMLTouchableHighlightElement extends Components.TouchableHighlight, HTMLStencilElement {}
  var HTMLTouchableHighlightElement: {
    prototype: HTMLTouchableHighlightElement;
    new (): HTMLTouchableHighlightElement;
  };

  interface HTMLTouchableOpacityElement extends Components.TouchableOpacity, HTMLStencilElement {}
  var HTMLTouchableOpacityElement: {
    prototype: HTMLTouchableOpacityElement;
    new (): HTMLTouchableOpacityElement;
  };

  interface HTMLTouchableScaleElement extends Components.TouchableScale, HTMLStencilElement {}
  var HTMLTouchableScaleElement: {
    prototype: HTMLTouchableScaleElement;
    new (): HTMLTouchableScaleElement;
  };
  interface HTMLElementTagNameMap {
    'touchable-blur': HTMLTouchableBlurElement;
    'touchable-elevate': HTMLTouchableElevateElement;
    'touchable-highlight': HTMLTouchableHighlightElement;
    'touchable-opacity': HTMLTouchableOpacityElement;
    'touchable-scale': HTMLTouchableScaleElement;
  }
}

declare namespace LocalJSX {
  interface TouchableBlur extends JSXBase.HTMLAttributes<HTMLTouchableBlurElement> {
    '_blur'?: number;
  }
  interface TouchableElevate extends JSXBase.HTMLAttributes<HTMLTouchableElevateElement> {
    'elevation'?: number;
  }
  interface TouchableHighlight extends JSXBase.HTMLAttributes<HTMLTouchableHighlightElement> {}
  interface TouchableOpacity extends JSXBase.HTMLAttributes<HTMLTouchableOpacityElement> {
    'opacity'?: number;
  }
  interface TouchableScale extends JSXBase.HTMLAttributes<HTMLTouchableScaleElement> {
    'scale'?: number;
  }

  interface IntrinsicElements {
    'touchable-blur': TouchableBlur;
    'touchable-elevate': TouchableElevate;
    'touchable-highlight': TouchableHighlight;
    'touchable-opacity': TouchableOpacity;
    'touchable-scale': TouchableScale;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


